import type { Book, Review } from "./types";

export const BOOKS: Book[] = [
  {
    id: "2001",
    slug: "book-2001",
    title: "SAMPLE BOOK 1",
    author: "AUTHOR 1",
    price: 458,
    discountPrice: 450,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2001.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2001.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2001_BC.JPG",
    ],
    rating: 4.5,
    reviewCount: 311,
    genres: ["Fiction", "Literary"],
    formats: ["Hardcover", "Paperback", "eBook"],
    description:
      "एक युवा लेखक की संघर्षपूर्ण यात्रा जो अपने सपनों और यथार्थ के बीच झूलता है। प्रेम, विश्वासघात और आत्म-खोज की यह गहन कहानी आपको सोचने पर मजबूर कर देगी।",
    pages: 248,
    isbn: "9788140685442",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2002",
    slug: "book-2002",
    title: "SAMPLE BOOK 2",
    author: "AUTHOR 2",
    price: 385,
    discountPrice: 418,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2002.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2002.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2002_BC.JPG",
    ],
    rating: 4.8,
    reviewCount: 456,
    genres: ["Romance", "Fiction"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "दिल्ली की हलचल भरी सड़कों पर दो दिलों की मुलाकात, जो दोस्ती से शुरू होकर गहरे प्रेम में बदल जाती है। भावुक और रोमांचक प्रेम कहानी जो दिल को छू लेगी।",
    pages: 421,
    isbn: "9788185650138",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2003",
    slug: "book-2003",
    title: "SAMPLE BOOK 3",
    author: "AUTHOR 3",
    price: 473,
    discountPrice: 225,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2003.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2003.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2003_BC.JPG",
    ],
    rating: 4.6,
    reviewCount: 361,
    genres: ["Mystery", "Thriller"],
    formats: ["Hardcover", "Paperback", "eBook"],
    description:
      "एक शांत कस्बे में हुई रहस्यमयी हत्या। हर व्यक्ति संदिग्ध लगता है और सच्चाई उजागर होने के साथ सस्पेंस चरम पर पहुंच जाता है।",
    pages: 382,
    isbn: "9788189398331",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2004",
    slug: "book-2004",
    title: "SAMPLE BOOK 4",
    author: "AUTHOR 4",
    price: 306,
    discountPrice: 373,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2004.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2004.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2004_BC.JPG",
    ],
    rating: 4.7,
    reviewCount: 491,
    genres: ["Historical", "Fiction"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "स्वतंत्रता संग्राम के दौरान एक युवा क्रांतिकारी की अनकही कहानी। देशभक्ति, बलिदान और प्रेम का मिश्रण जो इतिहास को जीवंत कर देता है।",
    pages: 394,
    isbn: "9788147759891",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2005",
    slug: "book-2005",
    title: "SAMPLE BOOK 5",
    author: "AUTHOR 5",
    price: 346,
    discountPrice: 151,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2005.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2005.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2005_BC.JPG",
    ],
    rating: 4.8,
    reviewCount: 203,
    genres: ["Self-Help", "Motivational"],
    formats: ["Hardcover", "Paperback", "Audiobook"],
    description:
      "जीवन बदलने वाली 21 शक्तिशाली आदतें। सफल लोगों के अनुभवों से सिखाया गया यह व्यावहारिक मार्गदर्शन आपको नई ऊर्जा और दिशा देगा।",
    pages: 269,
    isbn: "9788137866743",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2006",
    slug: "book-2006",
    title: "SAMPLE BOOK 6",
    author: "AUTHOR 6",
    price: 348,
    discountPrice: 307,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2006.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2006.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2006_BC.JPG",
    ],
    rating: 4.1,
    reviewCount: 146,
    genres: ["Spiritual", "Philosophy"],
    formats: ["Paperback", "eBook"],
    description:
      "आत्मा की शांति और आंतरिक खुशी की खोज। प्राचीन भारतीय दर्शन को आधुनिक जीवन से जोड़ती यह पुस्तक गहरी अंतर्दृष्टि प्रदान करती है।",
    pages: 440,
    isbn: "9788181687054",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2007",
    slug: "book-2007",
    title: "SAMPLE BOOK 7",
    author: "AUTHOR 7",
    price: 438,
    discountPrice: 180,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2007.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2007.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2007_BC.JPG",
    ],
    rating: 4.9,
    reviewCount: 373,
    genres: ["Romance", "Literary"],
    formats: ["Hardcover", "Paperback", "eBook"],
    description:
      "एक अनकही प्रेम कहानी जो समय और दूरी की दीवारों को पार करती है। भावनाओं से भरी यह साहित्यिक रचना दिल को स्पर्श करेगी।",
    pages: 437,
    isbn: "9788164460041",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2008",
    slug: "book-2008",
    title: "SAMPLE BOOK 8",
    author: "AUTHOR 8",
    price: 433,
    discountPrice: 430,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2008.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2008.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2008_BC.JPG",
    ],
    rating: 4.5,
    reviewCount: 207,
    genres: ["Comedy", "Fiction"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "जीवन की छोटी-छोटी मुश्किलों पर आधारित हल्का-फुल्का व्यंग्य। हंसते-हंसते सोचने पर मजबूर करने वाली मजेदार कहानी।",
    pages: 382,
    isbn: "9788146494311",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2009",
    slug: "book-2009",
    title: "SAMPLE BOOK 9",
    author: "AUTHOR 9",
    price: 478,
    discountPrice: 174,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2009.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2009.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2009_BC.JPG",
    ],
    rating: 4.7,
    reviewCount: 235,
    genres: ["Fantasy", "Fiction"],
    formats: ["Hardcover", "Paperback"],
    description:
      "एक जादुई दुनिया जहां सपने हकीकत बन जाते हैं। एक साधारण लड़के की रोमांचक यात्रा जो किस्मत और जादू के बीच फंस जाता है।",
    pages: 216,
    isbn: "9788142969596",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2010",
    slug: "book-2010",
    title: "SAMPLE BOOK 10",
    author: "AUTHOR 10",
    price: 420,
    discountPrice: 244,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2010.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2010.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2010_BC.JPG",
    ],
    rating: 4.4,
    reviewCount: 479,
    genres: ["Mystery", "Crime"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "मुंबई की अंधेरी गलियों में एक सीरियल किलर का आतंक। हर मोड़ पर नया ट्विस्ट और अंत तक सस्पेंस बनाए रखने वाली थ्रिलिंग कहानी।",
    pages: 271,
    isbn: "9788114565624",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2011",
    slug: "book-2011",
    title: "SAMPLE BOOK 11",
    author: "AUTHOR 11",
    price: 437,
    discountPrice: 380,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2011.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2011.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2011_BC.JPG",
    ],
    rating: 4.8,
    reviewCount: 376,
    genres: ["Historical", "Biography"],
    formats: ["Hardcover", "Paperback"],
    description:
      "एक विस्मृत स्वतंत्रता सेनानी की सच्ची जीवन गाथा। उनके संघर्ष और बलिदान की प्रेरणादायक कहानी जो इतिहास के पन्नों को फिर से जीवंत करती है।",
    pages: 298,
    isbn: "9788136507236",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2012",
    slug: "book-2012",
    title: "SAMPLE BOOK 12",
    author: "AUTHOR 12",
    price: 431,
    discountPrice: 249,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2012.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2012.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2012_BC.JPG",
    ],
    rating: 5.0,
    reviewCount: 179,
    genres: ["Self-Help", "Motivational"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "सफलता की सीढ़ियां चढ़ने के लिए जरूरी मानसिक शक्ति और रणनीतियां। यह पुस्तक आपको अपनी क्षमता को पहचानने और उसे निखारने में मदद करेगी।",
    pages: 476,
    isbn: "9788150455558",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2013",
    slug: "book-2013",
    title: "SAMPLE BOOK 13",
    author: "AUTHOR 13",
    price: 234,
    discountPrice: 359,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2013.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2013.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2013_BC.JPG",
    ],
    rating: 4.6,
    reviewCount: 345,
    genres: ["Fantasy", "Sci-Fi"],
    formats: ["Hardcover", "Paperback"],
    description:
      "भविष्य की एक काल्पनिक दुनिया जहां इंसान और मशीन के बीच सीमाएं धुंधली हो गई हैं। रोमांच और विचारों से भरी विज्ञान कथा।",
    pages: 362,
    isbn: "9788167218783",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2014",
    slug: "book-2014",
    title: "SAMPLE BOOK 14",
    author: "AUTHOR 14",
    price: 313,
    discountPrice: 396,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2014.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2014.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2014_BC.JPG",
    ],
    rating: 4.6,
    reviewCount: 500,
    genres: ["Romance", "Drama"],
    formats: ["Paperback", "eBook"],
    description:
      "परिवार की जिम्मेदारियों और व्यक्तिगत इच्छाओं के बीच फंसी एक महिला की कहानी। प्रेम और त्याग का सुंदर चित्रण।",
    pages: 350,
    isbn: "9788120728681",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2015",
    slug: "book-2015",
    title: "SAMPLE BOOK 15",
    author: "AUTHOR 15",
    price: 425,
    discountPrice: 262,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2015.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2015.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2015_BC.JPG",
    ],
    rating: 5.0,
    reviewCount: 210,
    genres: ["Thriller", "Crime"],
    formats: ["Hardcover", "Paperback", "Audiobook"],
    description:
      "एक पुलिस अधिकारी और एक अनजान हत्यारे के बीच चल रही बुद्धिमत्ता की जंग। हर अध्याय नया सस्पेंस लाता है।",
    pages: 427,
    isbn: "9788112436245",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2016",
    slug: "book-2016",
    title: "SAMPLE BOOK 16",
    author: "AUTHOR 16",
    price: 281,
    discountPrice: 369,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2016.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2016.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2016_BC.JPG",
    ],
    rating: 4.7,
    reviewCount: 119,
    genres: ["Spiritual", "Self-Help"],
    formats: ["Paperback", "eBook"],
    description:
      "ध्यान और mindfulness के माध्यम से तनाव मुक्त जीवन जीने का व्यावहारिक तरीका। शांति की तलाश में हर उम्र के पाठकों के लिए उपयोगी।",
    pages: 403,
    isbn: "9788170387770",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2017",
    slug: "book-2017",
    title: "SAMPLE BOOK 17",
    author: "AUTHOR 17",
    price: 446,
    discountPrice: 156,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2017.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2017.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2017_BC.JPG",
    ],
    rating: 4.9,
    reviewCount: 107,
    genres: ["Memoir", "Biography"],
    formats: ["Hardcover", "Paperback"],
    description:
      "एक सामान्य इंसान की असामान्य जीवन यात्रा। चुनौतियों से भरे अनुभव जो प्रेरणा और साहस सिखाते हैं।",
    pages: 167,
    isbn: "9788179506683",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2018",
    slug: "book-2018",
    title: "SAMPLE BOOK 18",
    author: "AUTHOR 18",
    price: 329,
    discountPrice: 262,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2018.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2018.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2018_BC.JPG",
    ],
    rating: 4.7,
    reviewCount: 476,
    genres: ["Fiction", "Literary"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "समाज की जटिलताओं और मानवीय संबंधों का गहरा विश्लेषण। साहित्यिक शैली में लिखी गई यह कहानी लंबे समय तक याद रहेगी।",
    pages: 287,
    isbn: "9788189508948",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2019",
    slug: "book-2019",
    title: "SAMPLE BOOK 19",
    author: "AUTHOR 19",
    price: 235,
    discountPrice: 151,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2019.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2019.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2019_BC.JPG",
    ],
    rating: 4.3,
    reviewCount: 58,
    genres: ["Comedy", "Fiction"],
    formats: ["Paperback"],
    description:
      "परिवार और रिश्तेदारों की दुनिया में होने वाली हंसी-मजाक भरी घटनाएं। हल्की-फुल्की पढ़ाई के लिए परफेक्ट किताब।",
    pages: 277,
    isbn: "9788167854253",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2020",
    slug: "book-2020",
    title: "SAMPLE BOOK 20",
    author: "AUTHOR 20",
    price: 427,
    discountPrice: 199,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2020.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2020.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2020_BC.JPG",
    ],
    rating: 4.3,
    reviewCount: 117,
    genres: ["Historical", "Fiction"],
    formats: ["Hardcover", "Paperback", "eBook"],
    description:
      "1947 के विभाजन के दौरान एक गांव की कहानी। दर्द, उम्मीद और मानवता का मार्मिक चित्रण जो दिल को छू जाता है।",
    pages: 400,
    isbn: "9788175792060",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2021",
    slug: "book-2021",
    title: "SAMPLE BOOK 21",
    author: "AUTHOR 21",
    price: 309,
    discountPrice: 395,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2021.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2021.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2021_BC.JPG",
    ],
    rating: 4.9,
    reviewCount: 126,
    genres: ["Philosophy", "Non-Fiction"],
    formats: ["Paperback", "eBook"],
    description:
      "जीवन के गहरे सवालों पर विचार-प्रधान चर्चा। सुख, दुख और अस्तित्व के अर्थ को समझने में मदद करने वाली दार्शनिक पुस्तक।",
    pages: 302,
    isbn: "9788131796527",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2022",
    slug: "book-2022",
    title: "SAMPLE BOOK 22",
    author: "AUTHOR 22",
    price: 366,
    discountPrice: 433,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2022.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2022.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2022_BC.JPG",
    ],
    rating: 4.6,
    reviewCount: 406,
    genres: ["Romance", "Fiction"],
    formats: ["Hardcover", "Paperback"],
    description:
      "दो अलग-अलग दुनिया से आने वाले दो लोगों की प्रेम यात्रा। बाधाओं के बावजूद प्यार की जीत की सुंदर कहानी।",
    pages: 483,
    isbn: "9788111400898",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2023",
    slug: "book-2023",
    title: "SAMPLE BOOK 23",
    author: "AUTHOR 23",
    price: 271,
    discountPrice: 152,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2023.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2023.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2023_BC.JPG",
    ],
    rating: 4.2,
    reviewCount: 441,
    genres: ["Thriller", "Mystery"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "एक पुरानी हवेली में छिपे राज। अतीत की गूंज और वर्तमान का खतरा एक साथ उजागर होता है।",
    pages: 467,
    isbn: "9788113687091",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2024",
    slug: "book-2024",
    title: "SAMPLE BOOK 24",
    author: "AUTHOR 24",
    price: 422,
    discountPrice: 311,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2024.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2024.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2024_BC.JPG",
    ],
    rating: 4.7,
    reviewCount: 84,
    genres: ["Science", "Non-Fiction"],
    formats: ["Hardcover", "Paperback"],
    description:
      "ब्रह्मांड और मानव मस्तिष्क के रहस्यों पर रोचक जानकारी। विज्ञान को सरल भाषा में समझाने वाली ज्ञानवर्धक पुस्तक।",
    pages: 488,
    isbn: "9788123011437",
    pubDate: "2023",
    isBestseller: false,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
  {
    id: "2025",
    slug: "book-2025",
    title: "SAMPLE BOOK 25",
    author: "AUTHOR 25",
    price: 265,
    discountPrice: 408,
    cover: "https://www.mehtapublishinghouse.com/images/prodimages/2025.JPG",
    gallery: [
      "https://www.mehtapublishinghouse.com/images/prodimages/2025.JPG",
      "https://www.mehtapublishinghouse.com/images/prodimages/2025_BC.JPG",
    ],
    rating: 4.1,
    reviewCount: 500,
    genres: ["Motivational", "Self-Help"],
    formats: ["Paperback", "eBook", "Audiobook"],
    description:
      "असफलताओं से उठकर सफलता हासिल करने की असली कहानियां और व्यावहारिक सलाह। प्रेरणा से भरी यह किताब आपको आगे बढ़ने का जोश देगी।",
    pages: 310,
    isbn: "9788164554939",
    pubDate: "2023",
    isBestseller: true,
    onSale: true,
    saleEnds: "2026-03-25T00:00:00",
  },
];

export const GENRES = [
  "Fiction",
  "Non-Fiction",
  "Fantasy",
  "Romance",
  "Mystery",
  "Thriller",
  "Sci-Fi",
  "Historical",
  "Self-Help",
  "Memoir",
  "Biography",
  "Classic",
  "Literary",
  "Comedy",
  "Science",
  "History",
];

export const TESTIMONIALS = [
  {
    id: "1",
    name: "Sarah M.",
    text: "Mehta Publishing House has completely changed how I discover new reads. The curated collections are absolutely wonderful!",
    rating: 5,
  },
  {
    id: "2",
    name: "James T.",
    text: "Fast shipping, beautiful packaging, and the best prices I've found online. My go-to bookstore.",
    rating: 5,
  },
  {
    id: "3",
    name: "Emily R.",
    text: 'The audiobook selection is incredible. I listen during my commute and have "read" more books than ever before.',
    rating: 4,
  },
  {
    id: "4",
    name: "David K.",
    text: "Love the recommendations engine. Every suggestion has been a hit. Already recommended to all my friends.",
    rating: 5,
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "1",
    name: "Alexandra P.",
    rating: 5,
    date: "Jan 15, 2026",
    text: "Absolutely captivating from start to finish. One of the best reads of the year!",
  },
  {
    id: "2",
    name: "Michael Chen",
    rating: 4,
    date: "Dec 3, 2025",
    text: "Beautifully written with complex characters. The ending was a bit rushed but still a wonderful story.",
  },
  {
    id: "3",
    name: "Laura Stevens",
    rating: 5,
    date: "Nov 20, 2025",
    text: "I could not put this down. Read it in one sitting and immediately bought copies for friends.",
  },
  {
    id: "4",
    name: "Robert J.",
    rating: 4,
    date: "Oct 8, 2025",
    text: "A thought-provoking narrative that stays with you long after you finish. Highly recommend.",
  },
  {
    id: "5",
    name: "Nina Walters",
    rating: 3,
    date: "Sep 15, 2025",
    text: "Good but not great. The middle section dragged a bit, though the themes were interesting.",
  },
];

export const COLLECTIONS = [
  { name: "Fiction", icon: "📚", count: 8 },
  { name: "Romance", icon: "💕", count: 4 },
  { name: "Mystery", icon: "🔍", count: 3 },
  { name: "Sci-Fi", icon: "🚀", count: 3 },
  { name: "Non-Fiction", icon: "📖", count: 4 },
  { name: "Self-Help", icon: "✨", count: 2 },
  { name: "Historical", icon: "🏛️", count: 3 },
  { name: "Classic", icon: "📜", count: 3 },
];
