import type { Book, Review } from './types';

export const BOOKS: Book[] = [
  {
    id: '1', slug: 'the-midnight-library',
    title: 'The Midnight Library', author: 'Matt Haig',
    price: 24.99, discountPrice: 18.99,
    cover: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop',
    ],
    rating: 4.5, reviewCount: 342, genres: ['Fiction', 'Fantasy'],
    formats: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
    description: 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.',
    pages: 304, publisher: 'Viking Press', isbn: '978-0-525-55947-4', pubDate: 'Sep 29, 2020',
    isBestseller: true, onSale: true, saleEnds: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2', slug: 'where-the-crawdads-sing',
    title: 'Where the Crawdads Sing', author: 'Delia Owens',
    price: 22.99,
    cover: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=600&fit=crop',
    ],
    rating: 4.7, reviewCount: 891, genres: ['Fiction', 'Mystery'],
    formats: ['Hardcover', 'Paperback', 'eBook'],
    description: 'For years, rumors of the "Marsh Girl" haunted Barkley Cove, a quiet town on the North Carolina coast.',
    pages: 384, publisher: 'G.P. Putnam\'s Sons', isbn: '978-0-735-21909-0', pubDate: 'Aug 14, 2018',
    isBestseller: true,
  },
  {
    id: '3', slug: 'atomic-habits',
    title: 'Atomic Habits', author: 'James Clear',
    price: 27.99, discountPrice: 21.99,
    cover: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop',
    gallery: [
      'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=600&fit=crop',
      'https://images.unsplash.com/photo-1518744386442-2d48ac1f0f8f?w=400&h=600&fit=crop',
    ],
    rating: 4.8, reviewCount: 1203, genres: ['Non-Fiction', 'Self-Help'],
    formats: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
    description: 'An easy & proven way to build good habits & break bad ones. Tiny changes, remarkable results.',
    pages: 320, publisher: 'Avery', isbn: '978-0-735-21156-8', pubDate: 'Oct 16, 2018',
    isBestseller: true, onSale: true, saleEnds: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4', slug: 'the-song-of-achilles',
    title: 'The Song of Achilles', author: 'Madeline Miller',
    price: 16.99,
    cover: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=600&fit=crop',
    rating: 4.6, reviewCount: 567, genres: ['Fiction', 'Romance', 'Historical'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'A tale of gods, kings, immortal fame, and the human heart — a devastatingly beautiful retelling of Homer\'s Iliad.',
    pages: 378, publisher: 'Ecco', isbn: '978-0-062-06062-3', pubDate: 'Aug 28, 2012',
    isNewRelease: false,
  },
  {
    id: '5', slug: 'project-hail-mary',
    title: 'Project Hail Mary', author: 'Andy Weir',
    price: 28.99, discountPrice: 22.99,
    cover: 'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?w=400&h=600&fit=crop',
    rating: 4.9, reviewCount: 723, genres: ['Fiction', 'Sci-Fi'],
    formats: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
    description: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself are finished.',
    pages: 496, publisher: 'Ballantine Books', isbn: '978-0-593-13520-4', pubDate: 'May 4, 2021',
    isBestseller: true, isNewRelease: true,
  },
  {
    id: '6', slug: 'educated',
    title: 'Educated', author: 'Tara Westover',
    price: 18.99,
    cover: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&h=600&fit=crop',
    rating: 4.4, reviewCount: 456, genres: ['Non-Fiction', 'Memoir'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'A memoir about a young girl who leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    pages: 352, publisher: 'Random House', isbn: '978-0-399-59050-4', pubDate: 'Feb 20, 2018',
  },
  {
    id: '7', slug: 'the-invisible-life-of-addie-larue',
    title: 'The Invisible Life of Addie LaRue', author: 'V.E. Schwab',
    price: 26.99, discountPrice: 19.99,
    cover: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400&h=600&fit=crop',
    rating: 4.3, reviewCount: 389, genres: ['Fiction', 'Fantasy', 'Romance'],
    formats: ['Hardcover', 'Paperback', 'eBook'],
    description: 'A life no one will remember. A story you will never forget. France, 1714: a young woman makes a bargain to live forever.',
    pages: 448, publisher: 'Tor Books', isbn: '978-0-765-38756-8', pubDate: 'Oct 6, 2020',
    isNewRelease: true, onSale: true, saleEnds: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '8', slug: 'the-silent-patient',
    title: 'The Silent Patient', author: 'Alex Michaelides',
    price: 17.99,
    cover: 'https://images.unsplash.com/photo-1518744386442-2d48ac1f0f8f?w=400&h=600&fit=crop',
    rating: 4.2, reviewCount: 612, genres: ['Fiction', 'Thriller', 'Mystery'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'Alicia Berenson\'s life is seemingly perfect. Until one evening her husband Gabriel returns home and she shoots him five times in the face.',
    pages: 325, publisher: 'Celadon Books', isbn: '978-1-250-30169-7', pubDate: 'Feb 5, 2019',
    isBestseller: true,
  },
  {
    id: '9', slug: 'klara-and-the-sun',
    title: 'Klara and the Sun', author: 'Kazuo Ishiguro',
    price: 25.99,
    cover: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&h=600&fit=crop',
    rating: 4.1, reviewCount: 278, genres: ['Fiction', 'Sci-Fi', 'Literary'],
    formats: ['Hardcover', 'Paperback', 'eBook'],
    description: 'From the Nobel Prize-winning author, a novel about an Artificial Friend who observes the world from her place in the store.',
    pages: 307, publisher: 'Knopf', isbn: '978-0-593-31817-1', pubDate: 'Mar 2, 2021',
    isNewRelease: true,
  },
  {
    id: '10', slug: 'the-house-in-the-cerulean-sea',
    title: 'The House in the Cerulean Sea', author: 'TJ Klune',
    price: 19.99,
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    rating: 4.8, reviewCount: 534, genres: ['Fiction', 'Fantasy', 'Romance'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'A magical island. A dangerous task. A burning secret. Linus Baker leads a quiet life as a caseworker.',
    pages: 398, publisher: 'Tor Books', isbn: '978-1-250-21728-8', pubDate: 'Mar 17, 2020',
    isBestseller: true,
  },
  {
    id: '11', slug: 'sapiens',
    title: 'Sapiens', author: 'Yuval Noah Harari',
    price: 24.99,
    cover: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400&h=600&fit=crop',
    rating: 4.5, reviewCount: 982, genres: ['Non-Fiction', 'History', 'Science'],
    formats: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
    description: 'A brief history of humankind. 100,000 years ago, at least six human species inhabited the earth. Today there is just one: us.',
    pages: 464, publisher: 'Harper', isbn: '978-0-062-31609-7', pubDate: 'Feb 10, 2015',
  },
  {
    id: '12', slug: 'circe',
    title: 'Circe', author: 'Madeline Miller',
    price: 17.99, discountPrice: 13.99,
    cover: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&h=600&fit=crop',
    rating: 4.6, reviewCount: 678, genres: ['Fiction', 'Fantasy', 'Historical'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'In the house of Helios, god of the sun, a daughter is born. But Circe is a strange child—not powerful, not beautiful.',
    pages: 400, publisher: 'Little, Brown', isbn: '978-0-316-55634-7', pubDate: 'Apr 10, 2018',
    onSale: true, saleEnds: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '13', slug: 'anxious-people',
    title: 'Anxious People', author: 'Fredrik Backman',
    price: 18.99,
    cover: 'https://images.unsplash.com/photo-1510172951991-856a654063f9?w=400&h=600&fit=crop',
    rating: 4.3, reviewCount: 312, genres: ['Fiction', 'Comedy', 'Mystery'],
    formats: ['Hardcover', 'Paperback', 'eBook'],
    description: 'A poignant comedy about a bank robbery, a hostage situation, and eight extremely anxious strangers.',
    pages: 352, publisher: 'Atria Books', isbn: '978-1-501-16017-8', pubDate: 'Sep 8, 2020',
    isNewRelease: true,
  },
  {
    id: '14', slug: 'the-seven-husbands-of-evelyn-hugo',
    title: 'The Seven Husbands of Evelyn Hugo', author: 'Taylor Jenkins Reid',
    price: 16.99,
    cover: 'https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?w=400&h=600&fit=crop',
    rating: 4.7, reviewCount: 845, genres: ['Fiction', 'Romance', 'Historical'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.',
    pages: 400, publisher: 'Atria Books', isbn: '978-1-501-13978-5', pubDate: 'Jun 13, 2017',
    isBestseller: true,
  },
  {
    id: '15', slug: 'dune',
    title: 'Dune', author: 'Frank Herbert',
    price: 18.99,
    cover: 'https://images.unsplash.com/photo-1446776858070-70c3d5ed6758?w=400&h=600&fit=crop',
    rating: 4.6, reviewCount: 1567, genres: ['Fiction', 'Sci-Fi', 'Classic'],
    formats: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
    description: 'Set on the desert planet Arrakis, Dune is the story of Paul Atreides, who would become the mysterious man known as Muad\'Dib.',
    pages: 688, publisher: 'Ace Books', isbn: '978-0-441-17271-9', pubDate: 'Sep 1, 1965',
  },
  {
    id: '16', slug: 'the-great-gatsby',
    title: 'The Great Gatsby', author: 'F. Scott Fitzgerald',
    price: 12.99,
    cover: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop',
    rating: 4.4, reviewCount: 2103, genres: ['Fiction', 'Classic', 'Literary'],
    formats: ['Paperback', 'eBook'],
    description: 'The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.',
    pages: 180, publisher: 'Scribner', isbn: '978-0-743-27356-5', pubDate: 'Apr 10, 1925',
  },
  {
    id: '17', slug: 'becoming',
    title: 'Becoming', author: 'Michelle Obama',
    price: 26.99, discountPrice: 19.99,
    cover: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop',
    rating: 4.8, reviewCount: 1432, genres: ['Non-Fiction', 'Memoir', 'Biography'],
    formats: ['Hardcover', 'Paperback', 'eBook', 'Audiobook'],
    description: 'An intimate, powerful, and inspiring memoir by the former First Lady of the United States.',
    pages: 448, publisher: 'Crown', isbn: '978-1-524-76313-8', pubDate: 'Nov 13, 2018',
    isBestseller: true,
  },
  {
    id: '18', slug: 'the-alchemist',
    title: 'The Alchemist', author: 'Paulo Coelho',
    price: 14.99,
    cover: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=600&fit=crop',
    rating: 4.3, reviewCount: 987, genres: ['Fiction', 'Fantasy', 'Self-Help'],
    formats: ['Paperback', 'eBook', 'Audiobook'],
    description: 'A magical fable about following your dreams, this masterpiece has inspired millions of readers around the world.',
    pages: 197, publisher: 'HarperOne', isbn: '978-0-062-31560-1', pubDate: 'Apr 15, 1993',
  },
];

export const GENRES = [
  'Fiction', 'Non-Fiction', 'Fantasy', 'Romance', 'Mystery', 'Thriller',
  'Sci-Fi', 'Historical', 'Self-Help', 'Memoir', 'Biography', 'Classic',
  'Literary', 'Comedy', 'Science', 'History',
];

export const TESTIMONIALS = [
  {
    id: '1', name: 'Sarah M.', text: 'BookHaven has completely changed how I discover new reads. The curated collections are absolutely wonderful!', rating: 5,
  },
  {
    id: '2', name: 'James T.', text: 'Fast shipping, beautiful packaging, and the best prices I\'ve found online. My go-to bookstore.', rating: 5,
  },
  {
    id: '3', name: 'Emily R.', text: 'The audiobook selection is incredible. I listen during my commute and have "read" more books than ever before.', rating: 4,
  },
  {
    id: '4', name: 'David K.', text: 'Love the recommendations engine. Every suggestion has been a hit. Already recommended to all my friends.', rating: 5,
  },
];

export const MOCK_REVIEWS: Review[] = [
  { id: '1', name: 'Alexandra P.', rating: 5, date: 'Jan 15, 2026', text: 'Absolutely captivating from start to finish. One of the best reads of the year!' },
  { id: '2', name: 'Michael Chen', rating: 4, date: 'Dec 3, 2025', text: 'Beautifully written with complex characters. The ending was a bit rushed but still a wonderful story.' },
  { id: '3', name: 'Laura Stevens', rating: 5, date: 'Nov 20, 2025', text: 'I could not put this down. Read it in one sitting and immediately bought copies for friends.' },
  { id: '4', name: 'Robert J.', rating: 4, date: 'Oct 8, 2025', text: 'A thought-provoking narrative that stays with you long after you finish. Highly recommend.' },
  { id: '5', name: 'Nina Walters', rating: 3, date: 'Sep 15, 2025', text: 'Good but not great. The middle section dragged a bit, though the themes were interesting.' },
];

export const COLLECTIONS = [
  { name: 'Fiction', icon: '📚', count: 8 },
  { name: 'Romance', icon: '💕', count: 4 },
  { name: 'Mystery', icon: '🔍', count: 3 },
  { name: 'Sci-Fi', icon: '🚀', count: 3 },
  { name: 'Non-Fiction', icon: '📖', count: 4 },
  { name: 'Self-Help', icon: '✨', count: 2 },
  { name: 'Historical', icon: '🏛️', count: 3 },
  { name: 'Classic', icon: '📜', count: 3 },
];
